server:
  port: 9000
  servlet:
    context-path: /spider

#thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  mvc:
    static-path-pattern: /static/**
##redis
  redis:
    database: 9
    host: 127.0.0.1
    password: gynshkjit21830
    port: 6388
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: 1000

#企业数据源文件信息
corp:
  substr-left-brackets: true
  allowed-origin:
    enable: false
    allowed-urls:
      - 127.0.0.1:9000
      - 127.0.0.1:9090
