#thymeleaf
spring:
##redis
  redis:
    database: 9
    host: 127.0.0.1
    password: gynshkjit21830
    port: 6388
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: 1000

#企业数据源文件信息
corp:
  substr-left-brackets: true
  allowed-origin:
    enable: false
    allowed-urls:
      - 127.0.0.1:9000
      - 127.0.0.1:9090
